### ISSUE TITLE
Suggestion - Date Range

### ISSUE THREAD

**Issue by chriskoch99** [DJF3/Webex-Message-space-archiver#1]
First off... just want to say thanks for creating an amazing tool.  Very useful and easy to use!

I'm wondering if it would be possible to add the ability to pull only messages between X and Y dates, rather than just the max days or messages.  This would be helpful if you're looking for messages from only a certain year or time period.

Thanks!

**Comment by ojchase** [comment]
+1

I'm using this not to archive the entire world but to keep track of important conversations. A subset of the message history is enough.

**Comment by DJF3** [comment]
Ok, to make sure I'm understanding this correctly: you would need the ability to extract messages:
- between 01-01-2021  and 20-05-2021    (jan 1st and may 20th)

Think I may have found a way to make this work and still keep message threads complete (i.e. if you want messages until May 5th, a message thread started on May 5th would still show all responses, even if these were added after May 5th)

**Comment by chriskoch99** [comment]
I think that's right, generally.  I'm really just trying to accommodate a periodic / scheduled archive scenario wherein I start with a full archive of a space on let's say 1/1/21, but then I want to do monthly archives to add to what I have already without doing fulls every time.  (This helps capture the full history over time in case messages get deleted etc. later.)  In the best case, we could optionally append the monthly extract to an expanding archive file over time.

An ability to just specify a date range that outputs to a new file gets the job done, though.  Could always append the new file manually in a script etc.

Thanks again!

**Comment by DJF3** [comment]
@chriskoch99 @ojchase  Send me a message on Webex(Teams) duittenb@cisco.com and I will share test code that allows you to specify a start- and end-date.

**Comment by ojchase** [comment]
I actually have the repository cloned and could switch branches easily enough. But realistically, my need for this only takes place every few weeks. I'm in no hurry and won't be a quick tester.

**Comment by DJF3** [comment]
A major update with _many_ fixes, including the fix for this request has just been posted [here](https://github.com/DJF3/Webex-Message-space-archiver)
Can you let me know if it is fixed?

**Comment by chriskoch99** [comment]
@DJF3 - I finally got around to testing this, and it seems to work well, with one small weirdness.   That is, if I use `maxtotalmessages = 17052021-25102022` it includes all the messages from May 17th 2021 through October 24th, but not actually including those from the 25th.   I would have expected setting the end date of 25102022 to actually include the ones from that day.   Maybe that's intended, and I'm just weird lol?

Thanks much for adding this very useful feature!   And sorry for taking so long!  Company increased its retention not long after my initial use, and it became less urgent.  ;)
