### ISSUE TITLE
Issue - subfolder creation fails when team name ends in trailing space

### ISSUE THREAD

**Issue by chriskoch99** [DJF3/Webex-Message-space-archiver#2]
Didn't realize one of our Teams spaces was named with a trailing space.  The archiver trips on this, per below:

```
Traceback (most recent call last):
  File "E:\temp\teams\webex-teams-space-archive.py", line 1030, in <module>
    os.makedirs(myAttachmentFolder + "/files/")
225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'Sample Space /files/'

```
Obviously the space name shouldn't have the trailing space, and I've renamed it, but FYI.

**Comment by DJF3** [comment]
This should now be fixed. I added ".strip()" to the line below in function get_roomname
`return str(returndata.strip())`
It removes leading/trailing spaces from the space name

**Comment by chriskoch99** [comment]
Awesome, thanks!

**Comment by DJF3** [comment]
closed
