### ISSUE TITLE
Final message not shown as threaded

### ISSUE THREAD

**Issue by ojchase** [DJF3/Webex-Message-space-archiver#3]
If the final message in a space is part of a thread, it is not shown in the final HTML as threaded. I confirmed the JSON has the appropriate parentId.

I've debugged this to the point of calculating threaded_message in the main message loop. A "list index out of range" is being thrown and so threaded_message=False. I suspect that behavior is reasonable for either nextitem or previousitem, but not the other.

**Comment by DJF3** [comment]
@ojchase  Thank you for reporting. I have found the fix. You have to remove 1 line of code that has no function anymore (except for causing this issue). 
Please remove the line containing:
`nextitem = float(abc[index+1])`
Can you confirm that fixes the problem?
Cheers!
DJ

**Comment by ojchase** [comment]
Next time I need to use this I'll be sure to check it out. Thanks!

**Comment by ojchase** [comment]
yes, this fixes it
