### ISSUE TITLE
ZeroDivisionError when maxtotalmessages < 21

### ISSUE THREAD

**Issue by ojchase** [DJF3/Webex-Message-space-archiver#4]
Given a config where `maxtotalmessages` has a value less than 21,

```
Traceback (most recent call last):
  File "webex-space-archive.py", line 1232, in <module>
    current_step = mycounter/progress_steps
ZeroDivisionError: division by zero
```

**Comment by DJF3** [comment]
Hello @ojchase 

Thank you for reporting this issue. The quick fix: 
- Below the line `progress_steps = int(statTotalMessages / 21)`
- Add a line with `if progress_steps < 1:  progress_steps = 1`

Pls let me know if this fixed your problem!

**Comment by ojchase** [comment]
I did something similar as a temporary workaround last time. I expect this will probably work, but I also expect it to have the same result as my workaround did, and break the proper functioning of the visual progress bar. I'll check next time I need the program.

**Comment by ojchase** [comment]
Confirmed. This does indeed fix overall execution, but does break the progress bar, which will stop at 5*statTotalMessages.
