### ISSUE TITLE
Soft returns / newlines are not shown (visually) in HTML output

### ISSUE THREAD

**Issue by ojchase** [DJF3/Webex-Message-space-archiver#8]
Example message from webex:
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/1005488/148859152-d484ae0d-bd28-4859-b4c8-e43e4ab57d02.png">

In the JSON output:
```
"text": "Here is something I just came across:\n\nLog4j version 2.15.0 has been released to address this flaw, but The Record reports that its fix merely changes a setting from \"false\" to \"true\" by default. Users who change the setting back to \"false\" remain vulnerable to attack. Luckily this means that servers running earlier versions of Log4j can mitigate the attack by changing that setting.\n\nASF says that \"this behavior can be mitigated by setting system property 'log4j2.formatMsgNoLookups' to 'true' or by removing the JndiLookup class from the classpath (example: zip -q -d log4j-core-*.jar org/apache/logging/log4j/core/lookup/JndiLookup.class)\" in earlier versions of Log4j if users can't upgrade to the 2.15.0 release."
```

HTML:
```
<div class="css_messagetext">Here is something I just came across:

Log4j version 2.15.0 has been released to address this flaw, but The Record reports that its fix merely changes a setting from "false" to "true" by default. Users who change the setting back to "false" remain vulnerable to attack. Luckily this means that servers running earlier versions of Log4j can mitigate the attack by changing that setting.

ASF says that "this behavior can be mitigated by setting system property 'log4j2.formatMsgNoLookups' to 'true' or by removing the JndiLookup class from the classpath (example: zip -q -d log4j-core-*.jar org/apache/logging/log4j/core/lookup/JndiLookup.class)" in earlier versions of Log4j if users can't upgrade to the 2.15.0 release.</div>
```

Rendered HTML:
<img width="1590" alt="image" src="https://user-images.githubusercontent.com/1005488/148859318-e1e96b9a-8cb5-40b2-8d76-357e2b252607.png">

**Comment by ojchase** [comment]
This is inconsistent. I have other cases that look fine.

**Comment by DJF3** [comment]
It almost looks like the HTML interpretation ignores `\n\n`.
Let me know if you see this happening again. 
(and thanks for providing the _exact information_ that is needed with your questions!)

**Comment by ojchase** [comment]
Oh it definitely keeps happening. I downloaded several archives yesterday and saw this several times. It's also not necessarily `\n\n`. I see it with single `\n` as well. It's just not consistent, but I haven't noticed a pattern yet.

(Thanks; I try. I'm a developer myself and know the pain of a vague bug!)

**Comment by DJF3** [comment]
@ojchase 
I found that "\n" in a message that has the _**TEXT**_ field but **_no HTML_** field is not interpreted.
Fixed. Replace: 
`data_text = convertURL(str(msg['text']))`
with
`        data_text = convertURL(str(msg['text']).replace("\n","<br>"))
`
The fix will be in the next (soon to be released) version.
Again, thanks for sharing!

**Comment by DJF3** [comment]
@ojchase  
A major update with _many_ fixes, including the fix for this problem has just been posted [here](https://github.com/DJF3/Webex-Message-space-archiver)
Can you let me know if it is fixed?
